#! /bin/sh

sxhkd &
compton &
xsetroot -cursor_name left_ptr

polybar bar &
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 0
bspc config window_gap 15
bspc config bottom_padding 35

bspc config pointer_follows_monitor true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle false

bspc config focus_follows_pointer true
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action3 resize_side
bspc config pointer_action3 resize_corner
