#! /bin/sh

sxhkd &
compton &
xsetroot -cursor_name left_ptr

polybar -r bar &
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 1
bspc config window_gap 15
bspc config bottom_padding 27

bspc config presel_feedback_color "#707880"
bspc config normal_border_color "#37474F"
bspc config focused_border_color "#707880"

bspc config pointer_follows_monitor true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle false

bspc config focus_follows_pointer true
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action3 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a Pinentry state=floating
