#!/bin/sh

sxhkd &
compton -b
xsetroot -cursor_name left_ptr
sh .fehbg
polybar -r bar &
nm-applet &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 2
bspc config window_gap 0

bspc config presel_feedback_color "#707880"
bspc config normal_border_color "#37474F"
bspc config focused_border_color "#707880"

bspc config pointer_follows_monitor true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle false

bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action3 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a Pinentry state=floating
bspc rule -a wineconsole.exe state=floating
bspc rule -a Emacs state=tiled

bspc rule -a scratchpad sticky=on state=floating hidden=on
kitty --class scratchpad -e ~/.bin/scratch &
