#!/bin/bash
bspc subscribe monitor | while read -r line; do
  case $line in
      monitor_add*|monitor_geometry*)
        killall polybar
        if [ "$(bspc query -M | wc -l)" -eq "2" ]; then
          MONITOR=$(bspc query -M --names | sed -n 1p) polybar bar &
          MONITOR=$(bspc query -M --names | sed -n 2p) polybar bar &
          bspc monitor $(bspc query -M | sed -n 1p) -d 1 2 3
          bspc monitor $(bspc query -M | sed -n 2p) -d 4 5 6 7 8 9 10
        else
          MONITOR=$(bspc query -M --names | sed -n 1p) polybar bar &
          bspc monitor -d 1 2 3 4 5 6 7 8 9 10
        fi
        ;;
      *)
      ;;
  esac
done &
