#!/bin/bash

dual_monitor() {
  if [ $(bspc query -M | wc -l) -eq "2" ]; then
    echo "There are already two monitors"
    exit 1
  fi
  focused=$(bspc query -d focused -D --names)
  xrandr --output DP-1-2 "$1" eDP-1 --auto
  MONITOR=DP-1-2 polybar bar &

  bspc desktop 1 -m DP-1-2
  bspc desktop 2 -m DP-1-2
  bspc desktop 3 -m DP-1-2
  bspc desktop Desktop -r
  bspc desktop -f $focused
}

case $1 in
  left)
    dual_monitor "--left-of"
  ;;
  right)
    dual_monitor "--right-of"
  ;;
  off)
    focused=$(bspc query -d focused -D --names)
    xrandr --output DP-1-2 --off
    killall -9 polybar
    polybar bar &
    bspc monitor eDP-1 -o 1 2 3 4 5 6 7 8 9 10
    bspc desktop -f $focused
  ;;
  *)
    echo "$(basename $0) left|right|off"
    exit 1
  ;;
esac
